# Generated by Django 5.0.1 on 2024-02-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('firstName', models.TextField(max_length=20)),
                ('lastName', models.TextField(max_length=20)),
                ('username', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('subscription', models.IntegerField(default=3)),
                ('streamID', models.TextField(default='null')),
            ],
        ),
    ]
