# Generated by Django 5.0.1 on 2024-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='streamNames',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
