# Generated by Django 5.0.1 on 2024-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cuser_streamnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='streamNames',
            field=models.TextField(max_length=10000),
        ),
    ]
